var translationsFA = {
    "font": "IranSans",
    "direction": "rtl",
    "float": "right",
    "h1": "30",
    "h2": "25",
    "h3": "20",
    "h4": "15",
    "h5": "10",
    "h6": "5",
    "title": "سامانه اعتبار سنجی نشانی شهروند",
    "menu_1": "تایید نشانی",
    "menu_2": "راهنما",
    "menu_3": "درخواست جدید",
    "menu_4": "رهگیری",
    "menu_5": "گزارش اشتباه",
    "menu_6": "ارسال مجدد",
    "menu_7": "ثبت شکایات",
    "menu_8": "درباره ما",
    "text_1": "اعتبار سنجی نشانی شهروند،",
    "text_2": "خدمتی است که شرکت ملی پست با همکاری شرکت رایانه روژینا، به اشخاص حقیقی و حقوقی( دولتی و خصوصی) این امکان را می دهد تا بر اساس ساز و کار اجرایی، صحت نشانی پستی مشتریان و مخاطبان خود را اعتبار سنجی نمایند، در این خدمت، نامه ای حاوی رمز (کد) ۶ رقمی اعتبار نشانی فرد مورد نظر تولید و در چرخه پستی جهت توزیع قرار می گیرد و مخاطب جهت تایید نشانی خود می بایست با استفاده از ابزار های ارتباطی و الکترونیکی (وب سایت، تلفن و پیامک) کد اعتبار سنجی خود را به سامانه اعلام نماید.",
    "text_3": "فرایند اجرایی سامانه",
    "text_4": "ارسال درخواست",
    "text_5": "تقاضای اعتبار سنجی نشانی شهروند توسط موسسه یا  خود شهروند به صورت آنلاین به سیستم ارسال می شود.",
    "text_6": "تحویل نامه",
    "text_7": "شرکت ملی پست نامه ای را حاوی یک رمز عددی چاپ و  برای نشانی شهروند ارسال می کند.",
    "text_8": "تایید نامه",
    "text_9": "شهروند نامه را دریافت و پس از مطالعه، کد ۶ رقمی اعتبار سنجی را از طریق این وب سایت و یا تلفن 02141924 و یا پیامک به سامانه ارسال می کند.",
    "text_10": "درخواست مجدد",
    "text_11": "اگر شهروند نامه اعتبار سنجی را گم کرد و یا نامه بدست وی نرسید، می تواند تقاضای ارسال مجدد کند. پرداخت هزینه ارسال مجدد توسط شهروند الزامی است",
    "text_12": "مطلع شدن سازمان",
    "text_13": "اعتبار سنجی نشانی شهروند به سازمان یا موسسه متقاضی نیز جهت اطلاع فوری ارسال می شود.",
    "text_14": "اعتبار سنجی نشانی",
    "text_15": "در صورت صحت کد ۶ رقمی اعتبار سنجی، سامانه بلافاصله نشانی شهروند را اعتبار سنجی می کند و به وی اطلاع می دهد.",
    "text_16": " شرکت ملی پست قبول و توزیع نامه های حاوی رمز یکتای اعتبار سنجی نشانی شهروندان را به عهده دارد. و شهروندان می بایست پس از دریافت نامه حداکثر ظرف دو هفته جهت اعتبار سنجی نشانی خود « رمز ۶ رقمی اعتبار سنجی » را به یکی از طرق ۱- مراجعه به این سایت ۲- تماس با شماره تلفن ۰۲۱۴۱۹۲۴ و روش سوم ارسال کد تایید به همراه کد تایید به شماره پیامکی( 02141924) اقدام نمایند. عدم اعلام کد ارسالی در مهلت تعیین شده، به مفهوم عدم تایید اعتبار نشانی پستی فرد تلقی گردیده و منجر به عدم ارائه خدمات و سرویسهای رسمی به مخاطب خواهد بود.",
    "text_17": "درخواست جدید برای اعتبار سنجی نشانی شهروند",
    "text_18": "شهروند گرامی، شما می توانید با مراجعه به بخش درخواست جدید، نسبت به اعتبار سنجی نشانی خود اقدام نمایید. درصورت تایید، نشانی تایید شده به مدت سه ماه در سیستم معتبر خواهد بود، لذا با مراجعه آنی به بانکها ویا سایر موسساتی که نیاز به اعتبار سنجی نشانی شما می باشد،  دیگر نیازی به انتظار برای دریافت نامه اعتبار سنجی نشانی را نخواهید داشت و سیستم به طور خودکار نشانی شما را اعتبار سنجی خواهد نمود",
    "text_19": "لطفا فرم زیر را به دقت تکمیل نمایید تا نامه اعتبار سنجی به نشانی شما ارسال شود . بسته به نوع سرویس پستی ، هزینه ارسال متفاوت خواهد بود و در مرحله بعد قابل مشاهده است .",
    "text_20": "توجه : تکمیل گزینه های ستاره دار الزامی می باشد.",
    "text_21": "نوع شخصیت",
    "text_22": "جنسیت",
    "text_23": "مرد",
    "text_24": "زن",
    "text_25": "رهگیری و مشاهده آخرین وضعیت نامه اعتبار سنجی",
    "text_26": "مخاطبین محترم، چنانچه نامه اعتبار سنجی تاکنون در نشانی اعلام شده به دست شما نرسیده است، می توانید با وارد کردن کد رهگیری، آخرین وضعیت نامه ارسالی را مشاهده نمایید. ضمنا در زمان تولید نامه، کد رهگیری به شماره تلفن همراه شما ارسال خواهد شد.",
    "text_27": "اعلام توزیع اشتباه در نشانی گیرنده",
    "text_28": "هموطن گرامی: چنانچه نامه دریافتی، اشتباها در نشانی شما توزیع و تحویل شما گردیده است و یا مطمئین هستید شخص نامبرده در نشانی درج شده بر روی پاکت حضور دائمی و قانونی ندارد، لطفا کد رهگیری نامه را بعلت « توزیع اشتباه در نشانی » در ذیل وارد نمایید.",
    "text_29": "ثبت درخواست ارسال مجدد نامه اعتبار سنجی نشانی",
    "text_30": "چنانچه پس از گذشت بیش از یک هفته از ثبت درخواست، نامه اعتبار سنجی به دست شما نرسیده، یا مهلت زمانی نامه جهت ثبت کد رمز ارسالی منقضی و یا رمز ارسالی مفقود گردیده باشد، می توانید نسبت به درخواست ارسال مجدد نامه اقدام نمایید. جهت ثبت درخواست ارسال مجدد لطفا در قسمت زیر کد پیگیری خود را وارد نمایید.",
    "text_31": "بدیهی است درخواست مجدد، مشمول پرداخت هزینه ارسال پستی است",
    "text_32": "ثبت نظر، شکایت و یا انتقاد",
    "text_33": "چنانچه درخصوص این سرویس پرسشی دارید و یا در خصوص اعتبار سنجی و تکمیل نشانی دچار مشکل شده اید، لطفا فرم زیر را تکمیل نمایید و شماره رهگیری خود را در صورت وجود وارد نمایید",
    "text_34": "طرح اعتبار سنجی نشانی شهروند با مشارکت شرکت ملی پست و شرکت رایانه روژینا به بهره برداری رسیده است. در این طرح، کلیه سازمانها و ارگانها و حتی شرکتهای خصوصی می توانند ضمن تماس با واحد بازرگانی شرکت رایانه روژینا در تهران، نسبت به عقد قرارداد دریافت سرویس اقدام نمایند. وب سرویس اعتبار سنجی نشانی، به سازمانها کمک می کند که بدون نیاز به داشتن تجهیزات و برنامه ریزی های متعدد نرم افزاری، براحتی و با کمک شبکه وسیع حمل و نقل پستی، اقدام به ارسال نامه اعتبار سنجی به مقصد مشتری یا متقاضی مربوطه نمایند. نامه اعتبار سنجی ارسالی، دارای یک کد رمز 6 رقمی است که شهروند به همراه کد ملی خود می تواند از طریق سامانه وب (همین سامانه) یا از طریق تلفن و پیامک اقدام به اعتبار سنجی نماید.",
    "text_35": " شرکت ملی پست  :",
    "text_36": "نشانی : تهران ، خیابان دکتر بهشتی ، بعد از بزرگراه مدرس ، شماره 267 ، ساختمان مرکزی شرکت پست ، طبقه سوم ، دفتر روابط عمومی شرکت پست جمهوری اسلامی ایران",
    "text_37": " شرکت رایانه روژینا :",
    "text_38": " نشانی : تهران ، خیابان شریعتی ، بالا تر از هویزه، کوچه جهاد، پلاک3، طبقه اول شرقی",
    "text_39": "شماره تماس:  88522948 - 88733022",
    "text_40": "عضو خبرنامه ما شوید",
    "text_41": "قوانین و مقررات",
    "text_42": "برای مشاهده قوانین و مقررات سایت روی لینک قوانین سایت کلیک نمایید",
    "text_43": "تماس",
    "text_44": "نشانی : تهران ، خیابان شریعتی ، بالا تر از هویزه، کوچه جهاد، پلاک3، طبقه اول شرقی",
    "text_45": "تلفن",
    "text_46": "وبسایت",
    "text_47": " تمامی حقوق برای",
    "text_48": "شرکت ملی پست",
    "text_49": "و شرکت رایانه روژینا",
    "text_50": "محفوظ می باشد",
    "text_51": "کد تایید",
    "text_52": "شماره ملی",
    "text_53": "نام *",
    "text_54": "نام خانوادگی *",
    "text_55": "شماره تلفن همراه *",
    "text_56": "ایمیل",
    "text_57": "نام شرکت *",
    "text_58": "شماره ملی *",
    "text_59": "شماره تلفن شرکت *",
    "text_60": "ایمیل شرکت / موسسه",
    "text_61": "کد پستی مکان فعلی شما *",
    "text_62": "نام استان",
    "text_63": "نام شهرستان",
    "text_64": " بخش/محله/دهستان",
    "text_65": "نام بخش / محله  / دهستان *",
    "text_66": " نوع معبر اصلی",
    "text_67": "معبر اصلی *",
    "text_68": "نوع معبر فرعی 1 ",
    "text_69": "معبر فرعی 1",
    "text_70": "نوع معبر فرعی 2 ",
    "text_71": "معبر فرعی 2",
    "text_72": "پلاک / شماره *",
    "text_73": "شماره واحد",
    "text_74": "نام ساختمان",
    "text_75": " ادامه به مرحله بعد",
    "text_76": "کد رهگیری",
    "text_77": "کد رهگیری در صورت وجود",
    "text_78": "ارسال گزارش",
    "text_79": "ارسال مجدد نامه",
    "text_80": "ارسال ",
    "text_81": "ایمیل شما",
    "text_82": "نام و نام خانوادگی",
    "text_83": "ایمیل",
    "text_84": "شماره تلفن همراه ",
    "text_85": "پرسش خود را در اینجا تایپ کنید",
    "text_86": "در صورتی که  نامه اعتبار سنجی نشانی بدست شما رسیده است،<br />لطفا کد ملی و کد رمز خود را در قسمت بالا وارد نمایید و دکمه تایید نشانی را فشار دهید.",
    "text_87": "همچنین می توانید برای اعتبار سنجی نشانی، با شماره 02141924 تماس بگیرید<br />و یا کدملی و کد رمز تایید را با درج یک فاصله بین آنها، به شماره 02141924 پیامک کنید.",
    "text_88": "اگر از مدت زمان انقضا نامه شما گذشته باشد،<br />  می توانید تقاضای ارسال مجدد کنید که نیاز به کد رهگیری نامه فعلی خواهید داشت.",
    "text_89": "مشخصات نامه اعتبار سنجی شما :",
    "text_90": "شخص حقیقی",
    "text_91": "شخص حقوقی",
    "lisense": "© 1395",
    "floor": "طبقه",
    "successful": "موفقیت آمیز",
    "error": "خطا",
    "Confirm": "تایید",
    "validation_1": "لطفا کد ملی 10 رقمی خود را وارد نمایید",
    "validation_2": "لطفا کد ۶ رقمی اعتبار سنجی خود را وارد نمایید",
    "validation_3": "کد رهگیری 10 تا 20 رقم می باشد، لطفا 10رقم تا 20 رقم وارد کنید",
    "validation_4": "لطفا پرسش خود را وارد نمایید",
    "validation_5": "لطفا نام خود را وارد نمایید",
    "validation_6": "لطفا نام خانوادگی خود را وارد نمایید",
    "validation_7": "لطفا کد ملی خود را وارد نمایید",
    "validation_8": "لطفا شماره تلفن همراه خود که با  09 آغاز میشود را وارد نمایید  ",
    "validation_9": "لطفا ایمیل  خود را وارد نمایید",
    "validation_10": "لطفا نام شرکت را وارد نمایید",
    "validation_11": "لطفا شماره ملی 13 رقمی شرکت را وارد نمایید",
    "validation_12": "لطفا شماره تلفن 11 رقمی شرکت را وارد نمایید ",
    "validation_13": "لطفا ایمیل شرکت / موسسه را وارد نمایید",
    "validation_14": "لطفا کد پستی 10 رقمی مکان خود را وارد نمایید",
    "validation_15": "لطفا نام استان  خود را انتخاب نمایید",
    "validation_16": "لطفا نام شهرستان  خود را انتخاب نمایید",
    "validation_17": "لطفا بخش، محله یا دهستان را انتخاب نمایید",
    "validation_18": "لطفا نام محله یا بخش  خود را وارد نمایید",
    "validation_19": "لطفا شماره پلاک   خود را وارد کنید",
    "validation_20": "لطفا شماره طبقه  خود را وارد کنید ",
    "validation_21": "لطفا شماره واحد  خود را وارد کنید ",
    "validation_22": "لطفا نام ساختمان خود را وارد کنید ",
    "text_92": "اطلاعات شما ثبت شد، پس از انتخاب نوع ارسال و پرداخت وجه ، نامه اعتبار سنجی برایتان ارسال میشود"
};
var translationsEN = {
    "font": "sans-serif",
    "direction": "ltr",
    "float": "left",
    "h1": "30",
    "h2": "25",
    "h3": "20",
    "h4": "15",
    "h5": "10",
    "h6": "5",
    "title": "Address Verification System for Citizens ",
    "menu_1": "Address Verification",
    "menu_2": "Help",
    "menu_3": "New Request",
    "menu_4": "Tracking",
    "menu_5": "False report",
    "menu_6": "Resend",
    "menu_7": "Complaints registration",
    "menu_8": "About Us",
    "text_1": "Address Verification System ",
    "text_2": "A service of Iran's national Post collaborating with Rojina Computer Ltd allowing natural and legal persons (public and private) to verify the address of their customers based on enforcement mechanisms. The service provides a letter contains of a 6-digit code that is being entered to the post cycle for distribution. The receiver should submit the code using electronic communication tools (website, telephone, SMS) into the portals. ",
    "text_3": "System Execution Process",
    "text_4": "Sending Request",
    "text_5": "The address verification request is sent online to the system by the institution or citizen.",
    "text_6": "Delivery of letter",
    "text_7": "National Post Office print a letter with a numeric code and sent it to the citizen's address.",
    "text_8": "Verify letter",
    "text_9": "The Citizen receive the letter and after reading it submit the 6 digit code to the portal using one of these methods (website, phone (021-41924) and SMS).",
    "text_10": "Reapply",
    "text_11": "If citizen lost the letter or it didn't arrive to right address, it is possible to reapply for a new letter. Sending a new letter requirs payment of the fee. ",
    "text_12": "Notifiying the organization ",
    "text_13": "verification of citizen's address will be sent to applicant's organization or institution for instant information.",
    "text_14": "verifying Address",
    "text_15": "if the entered 6digit verification code is valid, then the citizen's address immediately is being verified and system notifies the applicant.",
    "text_16": "National Post Office is responsible for the acceptance and distribution of letters contains unique verification code. And citizens must apply for credentials own address using one of these methods (website, call 021-41924, or sending verification code with their national code to 021-41924) after receiving the verification letter within two weeks. Otherwise it means the address of them is not verifies and consequently results in lack of formal services to the them.",
    "text_17": "A new request for validation citizenship",
    "text_18": "Dear citizen, you can go to the section of New Request to validate your address. If your address verification process is successfully done, then the address would remain as a verified and valid address in the system for three months. Therefore, if you go to a bank or other institutions that are required to validate your address, the system automatically do that with no need for you to do it again.",
    "text_19": "For receiving the << Address Verification letter >> on your current address, please fill out the form below carefully. Depending on the type of service the cost will vary and it is noticeable at the next step.",
    "text_20": "Note: Completing options marked with an asterisk are mandatory.",
    "text_21": "Person-Type",
    "text_22": "Gender",
    "text_23": "Men",
    "text_24": "Wemen",
    "text_25": "Track and view the latest status of a submitted verification letter",
    "text_26": "Dear audience, if you didn't receive the verification letter, it is possible to track the latest status of your letter by entering your tracking code. In addition, the tracking code will be sent to your mobile at the time of letter production.",
    "text_27": "Declaration of a wrong distribution in reciever's address",
    "text_28": "Dear compatriots: If you received a letter by mistake or you are sure that the person named on the envelope has no permanent or legal presence on the address, please enter << verification code >> to report wrong address distribution bellow.",
    "text_29": "submission of the request for resending verification letter",
    "text_30": "If you didn't receive the verification letter after one week or the expiration date of submitting the verification code is passed or loss of verification code, you can reapply for the verification process. To submit another request (reapply) please enter your tracking code bellow.",
    "text_31": "Obiousely reapply requires the payment of mailing fee",
    "text_32": "Submit comments, complaints or criticism",
    "text_33": "Incase of having any question about the service or facing any problem with the process of verification, please fill the form bellow",
    "text_34": "Address Verification Web Service is a RESTFUL webservice which helps the organization to easily track and verify the costumer address by sending secure automated letters to their home or work address registered on the database. The Address verification letter includes a 6-digit secrect code which the client should use it in combination with his national ID to verify his address. There are 3 options for clients to connect to AVS which are Phone, Web and SMS.",
    "text_35": " National Post Company of IRAN :",
    "text_36": "Address: Customer Service Dept, 3rd Floor, Central Building of Post Company, No. 267, Beheshti Street, Tehran, IRAN",
    "text_37": " Rojina Computer Ltd :",
    "text_38": "Address: Apt 1st East, No. 3, Jahad Alley, Shariaty Street, Tehran , IRAN",
    "text_39": "Contact :  88522948 - 88733022",
    "text_40": "Join our newsletter",
    "text_41": "Terms and Conditions",
    "text_42": "Click on the rule's link to see terms and conditions",
    "text_43": "Contact",
    "text_44": "Address: Apt 1st East, No. 3, Jahad Alley, Shariaty Street, Tehran , IRAN",
    "text_45": "Contact",
    "text_46": "Website",
    "text_47": "All rights is reserved for",
    "text_48": "National Post Company of IRAN ",
    "text_49": "and Rojina Computer Ltd",
    "text_50": ".",
    "text_51": "Code",
    "text_52": "national code",
    "text_53": "* First Name",
    "text_54": "* Last Naame",
    "text_55": "* Phone Number",
    "text_56": "Email",
    "text_57": "* Company Name",
    "text_58": "* National Code",
    "text_59": "* Company Phone Number",
    "text_60": "Company Email",
    "text_61": "* Postal Code for your current location",
    "text_62": "Province Name",
    "text_63": "City Name",
    "text_64": "Section / district / village",
    "text_65": "* Name of Section / district / village",
    "text_66": "Type of main road",
    "text_67": "* Name of main road",
    "text_68": "Secondary road type 1",
    "text_69": "Secondary road Name 1",
    "text_70": "Secondary road type 2",
    "text_71": "Secondary road Name 2",
    "text_72": "* No",
    "text_73": "Unit",
    "text_74": "Building",
    "text_75": "Continue to next step",
    "text_76": "tracking code",
    "text_77": "if there are tracking code",
    "text_78": "report sending",
    "text_79": "Resend verification letter",
    "text_80": "Send ",
    "text_81": "Email",
    "text_82": "Full Name",
    "text_83": "Email",
    "text_84": "Phone Number ",
    "text_85": "Type in your question here",
    "text_86": "if you receive the letter,<br/> please enter your national ID and verification code above and press Address Verification bottun.",
    "text_87": "Also it is possible to call (021-41924) for verifying the address or sending either National Code or 6digit code with a <br/> between as an SMS to (021-41924).",
    "text_88": "If your letter expiration time is passed you can reapply and then you need to have the current tracking code.",
    "text_89": " Specifications of verification letter :",
    "text_90": "natural person",
    "text_91": "legal person",
    "lisense": "2016 ©",
    "floor": "Floor",
    "successful": "successful",
    "error": "error",
    "Confirm": "Confirm",
    "validation_1": "Please enter your 10-digit national code",
    "validation_2": "Please enter your 6-digit code validation",
    "validation_3": " tracking code is 10 to 20-digit, please enter the 10 digits to 20 digits",
    "validation_4": "Please enter your question",
    "validation_5": "لطفا نام خود را وارد نمایید",
    "validation_6": "لطفا نام خانوادگی خود را وارد نمایید",
    "validation_7": "لطفا کد ملی خود را وارد نمایید",
    "validation_8": "لطفا شماره تلفن همراه خود که با  09 آغاز میشود را وارد نمایید  ",
    "validation_9": "لطفا ایمیل  خود را وارد نمایید",
    "validation_10": "لطفا نام شرکت را وارد نمایید",
    "validation_11": "لطفا شماره ملی 13 رقمی شرکت را وارد نمایید",
    "validation_12": "لطفا شماره تلفن 11 رقمی شرکت را وارد نمایید ",
    "validation_13": "لطفا ایمیل شرکت / موسسه را وارد نمایید",
    "validation_14": "لطفا کد پستی 10 رقمی مکان خود را وارد نمایید",
    "validation_15": "لطفا نام استان  خود را انتخاب نمایید",
    "validation_16": "لطفا نام شهرستان  خود را انتخاب نمایید",
    "validation_17": "لطفا بخش، محله یا دهستان را انتخاب نمایید",
    "validation_18": "لطفا نام محله یا بخش  خود را وارد نمایید",
    "validation_19": "لطفا شماره پلاک   خود را وارد کنید",
    "validation_20": "لطفا شماره طبقه  خود را وارد کنید ",
    "validation_21": "لطفا شماره واحد  خود را وارد کنید ",
    "validation_22": "لطفا نام ساختمان خود را وارد کنید ",
    "text_92": "اطلاعات شما ثبت شد، پس از انتخاب نوع ارسال و پرداخت وجه ، نامه اعتبار سنجی برایتان ارسال میشود"

};


